version: "3"
services:
  postgis:
    image: postgis/postgis:12-3.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .:/tmp/data/
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgis
